version: "3.8"

services:
  app:
    container_name: docs
    build: .
    ports:
      - 8722:8722
    command: "uvicorn --host '0.0.0.0' --port 8722 --reload true main:app"
    restart: unless-stopped
    volumes:
      - /mnt/busse/documents:/documents
      - ./archive:/archive
      - ./logs:/logs
      - ./main.py:/main.py
      - ./static:/static
